version: '3'

services:
  mysql:
    container_name: dev-mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
      - TZ=UTC
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
  redis:
    container_name: dev-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: unless-stopped

networks:
  default:

volumes:
  mysql:
  redis: